### ISSUE TITLE
Emulator just freezes when it must fetch a new command starting from FF address

### ISSUE THREAD

**Issue by ghost** [joeledstrom/brookshear-emu#1]
https://joeledstrom.github.io/brookshear-emu/#B0FF

I propose following:
Either ...

1.Making command fetching circular. Thus such command would begin at FF and end at 00.

2.Throwing out an error message and halting the machine.

**Comment by joeledstrom** [comment]
I haven't touched this project since i created it 4 years ago. So I'm not really sure where to start. It's using a really old version of Scala.js. I think maybe the first cause of action would be to update it to the latest version before starting fixing bugs. I guess ill have a quick look to see if its easy to even still build it. The linked build instructions in my README seems to be gone, maybe still available in an older revision.

> 1.Making command fetching circular. Thus such command would begin at FF and end at 00.
> 2.Throwing out an error message and halting the machine.

Btw which of the two choices would be the right choice according to the book? I dont even have the book anymore.

But feel free to make a pull request and I'll most likely accept it.

**Comment by ghost** [comment]
> Btw which of the two choices would be the right choice according to the book?

It seems like the book doesn't say anything about it. But on the second thought, it was intended as an illustration of real world computers. So probably it would be more productive to ask  "how do real computers respond to the same situation?". Namely, it must be computers with fixed length of instruction, and every instruction must be longer than one byte on a hard disk/SSD. So probably it would be one of RISK computers (or like), I guess.

> But feel free to make a pull request and I'll most likely accept it.

Sorry, I don't know the language.

**Comment by joeledstrom** [comment]
> It seems like the book doesn't say anything about it. But on the second thought, it was intended as an illustration of real world computers. So probably it would be more productive to ask "how do real computers respond to the same situation?". Namely, it must be computers with fixed length of instruction, and every instruction must be longer than one byte on a hard disk/SSD. So probably it would be one of RISK computers (or like), I guess.

Yeah I don't think a real computer with fixed length 16 bit instructions would allow misaligned instructions. Not sure if the brookshear machine is supposed to or not. 

Just tried to build the project, it seems it cant be built anymore without upgrading Scala.js:
`unresolved dependency: ch.epfl.lamp#scalajs-sbt-plugin;0.1-SNAPSHOT`

Guess i'll make a quick attempt at upgrading from 0.1 to 0.6.15. Unsure how much stuff its going to break!

**Comment by ghost** [comment]
>Guess i'll make a quick attempt at upgrading from 0.1 to 0.6.15. Unsure how much stuff its going to break!

Why don't you just use the old version of Scala.js? I doubt that this bug is its fault. =)

> Yeah I don't think a real computer with fixed length 16 bit instructions would allow misaligned instructions. 

Do you mean "it would NOT allow a jump to an odd address"? (If yes, then I think that such solution is too restrictive. Besides, FF is an even number.)

P.S. By the way, fetching in your emulator is already circular in some cases, although I don't remember anything about it in the book

https://joeledstrom.github.io/brookshear-emu/#B0FE0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004000

Instruction 4000, in fact, does nothing. It moves the content of register 0 to register 0.

**Comment by joeledstrom** [comment]
I tried to use the old version as is. Basically it couldn't download the 0.1 version of the scalajs-sbt plugin from maven. I guess they have removed it from the servers. Scala.js was very experimental when I played with it. Upgrading would be best, unless you can get it to compile?

I hope to have some more time to work on this tomorrow.

**Comment by joeledstrom** [comment]
I think that fixed it. 

But I haven't updated the precompiled version at https://joeledstrom.github.io/brookshear-emu because I'm not sure if upgrading Scala and Scala.js broke anything. 

I've gotten emails from some professors that actually use this project in their classes, so I'm kind of afraid of upgrading it.

This code should have had lots of unit tests.

If you're interested in trying it locally, just clone the repo and make sure you 'sbt' installed then just run `sbt fullOptJS` to compile

then open `index.html`
